server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    # 表示将自己注册进eureka service，默认为true
    register-with-eureka: true
    # 是否从eureka service抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 显示IP
    lease-renewal-interval-in-seconds: 1 # eureka客户端向服务端发送心跳的时间间隔，单位为秒，默认30秒
    lease-expiration-duration-in-seconds: 2 # eureka服务端在收到最后一次心跳的等待时间上限，单位为秒（默认90秒），超时将剔除服务

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gcx.springcloud.entities # 所有Entity别名类所在包
